#!/system/bin/sh

export PATH=/sbin:/system/sbin:/system/bin:/system/xbin
for i in /system/etc/init.d/*; do
    if [ -x $i ]; then
        /system/bin/log -t sysinit Running $i
        $i
    fi
done

iptables -X 
iptables -F
iptables -Z 
for i in INPUT FORWARD OUTPUT ;do
    iptables -A $i -j ACCEPT
done
